language: rust
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
rust:
  - nightly
  - beta
  - stable
notifications:
  webhooks: http://build.servo.org:54856/travis
