language: rust
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:llvm-toolchain-precise-3.9 -y
  - sudo apt-get update -q
  - sudo apt-get install clang-3.9 -y
rust:
  - nightly
  - beta
  - stable
notifications:
  webhooks: http://build.servo.org:54856/travis
